---

- name: Copy Domain.py template
  template:
    src: templates/domain.py
    dest: "/home/oracle/wls/weblogic/wls12213/wlserver/common/templates/scripts/wlst/"
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0640

- name: Creation of Domain for WLS 
  command: "{{ item }}"
  become_user: "{{ wls_user }}"
  args:
    chdir: "{{ wls_home }}"
  with_items:
    - sh /home/oracle/wls/weblogic/wls12213/oracle_common/common/bin/wlst.sh /home/oracle/wls/weblogic/wls12213/wlserver/common/templates/scripts/wlst/domain.py

- name: Start Domain 
  become: true
  command: "{{ item }}"
  become_user: "{{ wls_user }}"
  args:
    chdir: "/home/oracle/wls/weblogic/wls12213/user_projects/domains/{{ domain }}/"
  with_items:
    - sh startWebLogic.sh &
  register: start
- debug: var=start
