---

- name: Create directory ORACLE_HOME for Weblogic setup
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
  with_items:
    - "{{ oracle_home }}"
    - "{{ wls_home }}"
    - "{{ domain_home }}"
    - "{{ ori_home }}"


- name: Download Weblogic server tarfile
  unarchive: 
    src: https://storage.googleapis.com/yesudasm/fmw_12.2.1.3.0_wls_quick_Disk1_1of1.zip
    dest: "{{ wls_home }}"
    remote_src: yes
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0750


- name: Copy response template
  template:
    src: templates/silentinstall.j2
    dest: "{{ wls_home }}/silentinstall.rsp"
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0600

- name: Copy OraInst.loc file
  copy:
    src: files/oraInst.loc
    dest: "{{ ori_home }}"
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0600

- name: Install using silent installation
  command: "{{ item }}"
  become_user: "{{ wls_user }}"
  args:
    chdir: "{{ wls_home }}"
  with_items:
    - java -jar fmw_12.2.1.3.0_wls_quick.jar -silent -responseFile {{ wls_home }}/silentinstall.rsp -invPtrLoc {{ ori_home }}/oraInst.loc   
