---

- name: Create directory ORACLE_HOME for Weblogic setup
  file:
    path: "{{ oracle_home }}"
    state: directory
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"

- name: Create directory ORACLE_HOME for Weblogic setup
  file:
    path: "{{ wls_home }}"
    state: directory
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"

me: Create directory ORACLE_HOME for Weblogic setup
  file:
    path: "{{ oracle_home }}"/oraInventory
    state: directory
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"



- name: Download Oracle weblogic server
  copy: 
    src: files/fmw_12.2.1.3.0_wls_quick_Disk1_1of1.zip
    dest: /home/oracle
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0750

- name: Unzip WLS
  unarchive:
    src: "/home/oracle/fmw_12.2.1.3.0_wls_quick_Disk1_1of1.zip"
    dest: "/home/oracle/"
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0750

- name: Copy response template
  template:
    src: silentinstall.j2
    dest: /home/oracle/silentinstall.txt
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0600

- name: Copy OraInst.loc file
  copy:
    src: files/oraInst.loc
    dest: "{{ wls_home }}"
    owner: "{{ wls_user }}"
    group: "{{ wls_group }}"
    mode: 0600

- name: Install using silent installation
  command: "{{ item }}"
  become_user: "{{ wls_user }}"
  args:
    chdir: "{{ oracle_home }}"
  with_items:
    - java -jar fmw_12.2.1.3.0_wls_quick.jar -silent -responseFile {{ oracle_home }}/silentinstall.txt -invPtrLoc {{ wls_home }}/oraInst.loc   


